services:
  - type: web
    name: job-tracker
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app --config gunicorn.conf.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
