services:
  - type: web
    name: job-tracker
    env: python
    buildCommand: |
      apt-get update && apt-get install -y python3-dev build-essential libjpeg-dev zlib1g-dev libxml2-dev libxslt1-dev
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app --config gunicorn.conf.py
